// Documentary-style blog cover metadata — batch 8.
// Prompts follow the mandatory template; alts in EN, concepts in VI.
export const COVERS = {
  "when-the-machine-is-faster-than-you": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young designer leaning back from a glowing laptop late at night, a freshly generated app interface on the screen, set in a small dim home-studio corner of a Vietnamese apartment lit by a single desk lamp, representing the quiet awe and faint sting of watching a machine do in seconds what took you months to learn. The scene includes one hand still resting on the trackpad and a half-turned posture caught between admiration and self-doubt, and a paper notebook of hand-sketched wireframes pushed aside, a cold mug, a phone lying face-down, and crooked sticky notes on the wall. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young designer leaning back from a glowing laptop at night, hand-drawn wireframes pushed aside on the desk.`,
    imageConcept: `Người trẻ ngồi trước màn hình AI vẽ ra giao diện trong khi bản nháp tay bị đẩy sang bên — vừa nể vừa chạnh lòng, đúng tinh thần bài về việc cố gắng khi máy nhanh hơn mình.`,
    needsRegeneration: true,
  },
  "you-cant-learn-to-swim-from-the-shore": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person sitting on the wet tiled edge of a quiet public swimming pool at dusk, feet dipped in the water just before pushing off, set in a modest local pool with fading evening light on the surface, representing the moment of stopping all the over-planning and finally daring to begin. The scene includes shoulders hunched forward in hesitation and a hand gripping the pool edge, and a folded towel beside them, droplets running down the calves, an untouched water bottle, and soft ripples spreading across the lane. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person sitting on the edge of a pool at dusk, feet in the water, hesitating before jumping in.`,
    imageConcept: `Cảnh do dự bên mép hồ trước khi nhảy xuống nước thể hiện thông điệp: không thể học bơi bằng cách đứng trên bờ — phải bắt tay vào làm.`,
    needsRegeneration: true,
  },
  "you-dont-have-to-be-the-sun": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person eating a simple bowl of instant noodles with a fried egg at a small kitchen table late in the evening, relaxed and quietly content, set in a tiny apartment kitchen with warm light and a soft city glow through the window, representing the peace of an ordinary life that is not a failure. The scene includes chopsticks paused mid-bite and a loose, unhurried posture, and a half-drunk glass of water, a phone lying face-down on the table, worn house slippers on the tiled floor, and a small potted plant on the sill. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person eating a simple bowl of noodles at a small kitchen table at night, content and unhurried.`,
    imageConcept: `Bữa tối giản dị một mình, bình yên, phố lên đèn ngoài cửa — đúng thông điệp bình phàm không phải thất bại, không cần làm mặt trời.`,
    needsRegeneration: true,
  },
  "you-dont-have-to-have-it-all-figured-out": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person standing alone at a busy city intersection at dusk, backpack hanging off one shoulder, looking out at the streaming motorbike traffic and unsure which way to go, set in a Vietnamese urban crossroads wrapped in golden-hour haze, representing the honest uncertainty of being young and not having it all figured out. The scene includes a slightly slumped, searching posture and a head turned toward the passing flow, and a backpack strap clutched in one hand, a phone held but not looked at, a canvas tote bag, and blurred scooter headlights and traffic lights behind. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person with a backpack standing at a city crossroads at dusk, watching the motorbike traffic go by.`,
    imageConcept: `Người trẻ đứng ở ngã tư chiều nhìn dòng xe, chưa biết rẽ đâu — hình ảnh đời thường của việc còn mơ hồ định hướng nhưng vẫn ổn.`,
    needsRegeneration: true,
  },
  "you-dont-owe-anyone-a-filter": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person sitting on the floor of a bedroom holding a phone up to the front camera in plain morning light, lowering it mid-selfie and choosing not to retouch their face, set in an ordinary bedroom with soft daylight from a curtained window, representing the quiet decision to stop apologizing for a real, unfiltered appearance. The scene includes a relaxed, slightly self-amused expression and natural untouched skin texture, and an unmade bed behind, a hair tie around the wrist, slightly messy hair, and a glass of water on the floor, the phone screen kept dim and blank. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person lowering their phone mid-selfie in a bedroom in soft morning light, bare unretouched skin.`,
    imageConcept: `Khoảnh khắc hạ điện thoại xuống, không chỉnh filter, để da mộc trong ánh sáng thật — đúng thông điệp ngừng xin lỗi vì vẻ ngoài nguyên bản.`,
    needsRegeneration: true,
  },
  "your-own-timezone-of-success": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person on a sofa lowering their phone after scrolling past a friend's good news, then turning back to a small task resting in their lap, set in a small apartment living room under a warm evening lamp, representing the choice to live on your own timeline instead of comparing it to everyone else's. The scene includes a calm, resolved posture and eyes drifting from the screen back to the work in hand, and a phone laid face-down on the cushion, a notebook open to a half-written page, a mug within reach, and socked feet tucked up under a soft blanket. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person setting their phone face-down on the sofa and turning back to a notebook under a warm lamp.`,
    imageConcept: `Đặt điện thoại xuống sau khi thấy thành tựu của bạn bè rồi quay lại việc nhỏ của mình — hình ảnh sống theo múi giờ riêng, ngừng so timeline.`,
    needsRegeneration: true,
  },
  "youre-not-running-late": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person standing alone at an evening bus stop watching a bus pull away down the street, calm rather than panicked, hands in their pockets, set in a Vietnamese city street under warm streetlight with faint reflections on the wet road, representing the quiet realization that you are not actually running late on your own life. The scene includes a steady, unhurried stance and a soft gaze following the departing bus, and a canvas tote bag on one shoulder, a paper cup of tea in one hand, the red tail-lights of the bus glowing in the distance, and a faint mist of breath in the cool air. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person at a night bus stop calmly watching a bus pull away, a paper cup of tea in hand.`,
    imageConcept: `Đứng ở trạm xe buýt tối nhìn chuyến vừa rời một cách bình thản — đúng tinh thần Time Anxiety: bạn không hề trễ chuyến nào của đời mình.`,
    needsRegeneration: true,
  },
  "not-every-storm-comes-to-wreck-you": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person sitting alone at a desk late at night, thumb resting on a phone screen mid-decision while a few small keepsakes lie scattered nearby, set in a quiet bedroom lit only by a small lamp, representing the quiet moment of letting go of a relationship that no longer fits. The scene includes a still hand hovering over the phone and a calm, tired but unburdened expression, and an old movie ticket and a folded handwritten note on the desk, a cold half-finished mug of tea pushed to the edge, a window with rain-streaked glass behind reflecting the lamp, and a single picture frame turned face-down. Warm natural light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person at a lamplit desk late at night, thumb resting on a phone, an old ticket and folded note beside a cold mug.`,
    imageConcept: `Tay dừng trên màn hình điện thoại lúc khuya với vé phim cũ, mẩu giấy nhắn và khung ảnh úp mặt — khoảnh khắc buông một người không còn phù hợp sau cơn bão.`,
    needsRegeneration: true,
  },
};
