// Documentary-style cover metadata — batch 7. Merged into OVERRIDES by
// lib/blog-image-prompt.mjs. Each prompt is a candid, human, story-driven scene.

export const COVERS = {
  "the-romance-of-private-failures": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a tired young woman sitting alone on the concrete steps of an apartment-block stairwell late at night, seen from the side and slightly behind so her face stays unclear, set in a dim Vietnamese walk-up building with a single flickering fluorescent light overhead, representing the quiet dignity of the failures no one else ever sees. The scene includes her shoulders sagging against the wall while she still grips a worn planner notebook, and honest details — scuffed sneakers, a canvas tote bag slumped on the step beside her, a half-finished bottle of water, house keys still in her hand. Warm natural light mixed with cool stairwell light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A tired young woman resting on a dim apartment stairwell at night, still holding a worn planner.`,
    imageConcept: `Ngồi nghỉ trên cầu thang chung cư khuya mà vẫn ôm cuốn sổ kế hoạch — những lần thất bại âm thầm không ai thấy nhưng vẫn không bỏ cuộc.`,
    needsRegeneration: true,
  },
  "the-shield-we-call-perfectionism": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young designer hunched over a laptop very late at night, photographed from just behind her shoulder so her face is hidden, set in a small dim bedroom-office lit only by the cold glow of the screen and one warm desk lamp, representing the exhaustion hidden behind perfectionism. The scene includes her hand frozen on the trackpad nudging a single tiny detail back and forth, and honest details — a cold, barely-touched cup of tea, crumpled sticky notes, a hoodie draped over the chair, a slumped late-night posture. Warm lamp light against cool screen light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young designer hunched over a laptop late at night, endlessly nudging one tiny detail.`,
    imageConcept: `Thức khuya chỉnh đi chỉnh lại một chi tiết nhỏ đến kiệt sức — cầu toàn là tấm khiên che nỗi sợ, không phải tiêu chuẩn cao.`,
    needsRegeneration: true,
  },
  "the-stranger-on-the-bus": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of two strangers sitting side by side on a late-afternoon city bus — a young commuter and an elderly passenger mid-conversation, both in soft profile and partial silhouette so faces are not identifiable, set inside a worn Vietnamese public bus with warm street light and neon shopfronts smearing past the window, representing an unexpected moment of human warmth in an ordinary commute. The scene includes the older person's weathered hand gesturing gently while the younger one leans in to listen, and grounding details — a canvas tote on a lap, a paper ticket, worn handrails, condensation on the glass, blurred motorbikes outside. Warm golden-hour light through the bus window, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `Two strangers, one young and one elderly, talking gently on a city bus in warm afternoon light.`,
    imageConcept: `Hai người lạ trò chuyện trên chuyến xe buýt chiều — thế giới vẫn còn tình người ấm áp giữa nhịp sống vội.`,
    needsRegeneration: true,
  },
  "the-trap-of-romanticizing-sadness": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young woman standing at a small bathroom sink in early morning light, just after washing her face, seen from behind toward a fogged, only half-clear mirror so her reflection stays soft and unidentifiable, set in a modest tiled Vietnamese bathroom, representing the decision not to let sadness become your whole identity. The scene includes water still dripping from her chin as one hand reaches for a towel, and honest details — a damp face towel, droplets sliding down the mirror, a tube of skincare on the ledge, soft warm light through a frosted window. Warm gentle morning light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young woman at a small bathroom sink in soft morning light, just after washing her face.`,
    imageConcept: `Sáng hôm sau rửa mặt trước gương — chọn bước tiếp thay vì để nỗi buồn trở thành toàn bộ con người mình.`,
    needsRegeneration: true,
  },
  "the-worst-one-in-the-room": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young student sitting alone in the back row of a crowded innovation-hub auditorium, viewed from behind over rows of heads so no face is identifiable, while a confident presenter stands blurred at the bright stage far ahead, representing the quiet ache of feeling like the least capable person in a room full of brilliant people. The scene includes the student's slightly hunched shoulders and a hand resting on a plain notebook of beginner course modules, and grounding details — a backpack between the feet, a lanyard, a half-finished water bottle, warm stage light glowing in the distance. Warm directional auditorium light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young student sitting at the back of a crowded auditorium as someone presents on the bright stage.`,
    imageConcept: `Ngồi hàng ghế cuối nhìn người khác tự tin thuyết trình — cảm giác kém nhất trong căn phòng giỏi, nhưng vẫn ở lại cố gắng.`,
    needsRegeneration: true,
  },
  "twenty-one-is-not-a-deadline": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a twenty-one-year-old sitting on the floor of a small rented room at night, back against the side of the bed with a laptop balanced on the knees just after sending an internship application, seen from the side so the face stays unclear, set in a cramped Vietnamese student room, representing the wobbly in-between of being young and unsure that twenty-one is not a deadline. The scene includes a slow exhale in the slumped posture and a hand fallen away from the keyboard, with honest details — a printed CV marked up with pen, an unmade bed, a small desk fan, a half-finished instant-noodle bowl, faint fairy lights on the wall. Warm low lamplight, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person sitting on the floor of a small room at night with a laptop, just after sending an application.`,
    imageConcept: `Bấm gửi đơn thực tập rồi ngồi thở dài trong phòng trọ nhỏ — tuổi 21 chênh vênh nhưng chưa phải hạn chót.`,
    needsRegeneration: true,
  },
  "what-the-psychology-of-money-taught-me": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young person at a small kitchen dining table on a quiet end-of-month evening, going over a handwritten spending notebook beside a dog-eared paperback, seen from the side with the face lowered and out of focus, set in a modest Vietnamese apartment kitchen under warm overhead light, representing a grounded, behavior-first way of thinking about money. The scene includes a hand resting on the open ledger page in a paused, thoughtful posture, with honest details — a few coins and folded receipts, a small calculator, a glass of water, a rice cooker softly steaming in the background. Warm kitchen light, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A young person at a small kitchen table at night, reviewing a handwritten spending notebook beside a paperback.`,
    imageConcept: `Xem lại sổ chi tiêu cuối tháng bên cuốn sách — cách nghĩ về tiền dựa trên hành vi và sự trưởng thành, đúng tinh thần cuốn sách.`,
    needsRegeneration: true,
  },
  "when-kindness-gets-used": {
    imagePrompt: `Ultra realistic candid documentary lifestyle photography of a young office worker alone at a desk in a half-empty office late in the evening, quietly taking on a stack of someone else's work, seen from behind and to the side so the face is not identifiable, set in a dim Vietnamese open-plan office where most of the lights are already switched off, representing kindness slowly being taken advantage of and the need for boundaries. The scene includes weary shoulders and a hand rubbing the back of the neck while a phone on the desk lights up with yet another request, plus honest details — two used coffee cups, a tote bag still hanging on the chair, a coat draped over the seat, blurred city lights through the window. Warm desk lamp glowing against the dark office, cinematic realism, 35mm photography, shallow depth of field, natural skin texture, subtle film grain, imperfect real-life composition, emotionally quiet but deeply human. No text, no logo, no watermark, no brand names, no celebrity, no recognizable face, no corporate stock photo, no cartoon, no 3D render.`,
    imageAlt: `A tired young worker alone at a desk in a dim, nearly empty office late at night.`,
    imageConcept: `Ở lại làm hộ việc trong văn phòng tối muộn — sự tử tế bị lợi dụng và nhu cầu đặt ra ranh giới.`,
    needsRegeneration: true,
  },
};
